apiVersion: v1
kind: Secret
metadata: 
  name: magento-mysql-secret
  namespace: magento
type: Opaque
stringData:
  MYSQL_USER: magento-user
  MYSQL_PASSWORD: magento-password
  MYSQL_DATABASE: magento-databse
  MYSQL_ROOT_PASSWORD: magento-root-password

