apiVersion: v1
kind: Service
metadata:
  name: magento-mysql
  namespace: magento
  labels:
    app: magento-mysql
spec:
  selector:
    app: magento-mysql
  ports: 
  - name: default-port
    port: 3306
    protocol: TCP
  type: NodePort
