apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento-nginx
  namespace: magento
  labels:
    app: magento-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magento-nginx
  template:
    metadata:
      labels:
        app: magento-nginx
    spec:
      containers:
      - name: magento-nginx
        image: magento/magento-cloud-docker-nginx 
        ports:
        - containerPort: 80
        volumeMounts:
        - name: magento-nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: magento-nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: vhost.conf
      volumes:
      - name: magento-nginx-config
        configMap:
          name: magento-nginx-config
